### ISSUE TITLE
saveAsNTriplesFile creates folder not file

### ISSUE THREAD

**Issue by carstendraschner** [SANSA-Stack/SANSA-Stack#98]
When I call saveAsNTriplesFile as described in examples or as in Sansa stack faq, I get a folder with the described path but inside are a success file and a list of partial nt formatted  files. they have a name: part-XXXXX (X for some Number). those files contain partial data for the desired file. A can of method: ".coalesce(1, shuffle = true)" leads to a folder with two files. one success and one merged part-00000 file. this is closer to what I want but is not what I or others would expect, right?

**Comment by JNKHunter** [comment]
You're describing the expected behavior of normal spark operation. The coalesce(1) method moves all data to a single partition, and writes all data out to a single partition file. This approach works for smaller data sets but as your data grows larger your job will run slower.

**Comment by LorenzBuehmann** [comment]
Nothing to fix here as this is the expected behaviour of Spark.

As already mentioned, using `coalesce(1)` or `repartition(1)` may work for small data-sets, but large data-sets would all be thrown into one partition on one node. This is likely to throw OOM errors, or at best, to process slowly.

For Hadoop 2.x I would highly suggest that you use the [`FileUtil.copyMerge()`](https://hadoop.apache.org/docs/stable/api/org/apache/hadoop/fs/FileUtil.html#copyMerge(org.apache.hadoop.fs.FileSystem,%20org.apache.hadoop.fs.Path,%20org.apache.hadoop.fs.FileSystem,%20org.apache.hadoop.fs.Path,%20boolean,%20org.apache.hadoop.conf.Configuration,%20java.lang.String)) function from the Hadoop API. This will merge the outputs into a single file.

With Hadoop 3.x this method has been removed though:
https://issues.apache.org/jira/browse/HADOOP-12967
https://issues.apache.org/jira/browse/HADOOP-11392
The best practice will be to use `getmerge`:
Usage: `hadoop fs -getmerge [-nl]`

Takes a source directory and a destination file as input and concatenates files in `src` into the destination local file. Optionally `-nl` can be set to enable adding a newline character (LF) at the end of each file. `-skip-empty-file` can be used to avoid unwanted newline characters in case of empty files. 

Example:
`hadoop fs -getmerge -nl /data.nt /opt/data.nt`
